version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/tre-sqs-sf-trigger"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/tre-sqs-sf-trigger"
    schedule:
      interval: "daily"
